# Generated by Django 2.2.3 on 2019-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='../static/img/noimage.jpg', upload_to='', verbose_name='Фотография профиля'),
        ),
    ]
