# Generated by Django 2.2.3 on 2019-07-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190713_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='../static/img/noimage.jpg', upload_to='media/', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_persone',
            field=models.CharField(choices=[('T', 'Преподователь'), ('S', 'Студент')], default='S', max_length=1, verbose_name='Кем хотите быть на teach.ua'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
