# Generated by Django 2.2.3 on 2019-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190713_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('L', 'low'), ('M', 'middle'), ('V', 'vip')], default='L', max_length=1),
        ),
    ]
