# Generated by Django 2.2.3 on 2019-07-25 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190717_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.URLField(default='../static/img/noimage.jpg', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='_user_like_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_persone',
            field=models.CharField(choices=[('T', 'Преподователь'), ('S', 'Ученик')], default='S', max_length=1, verbose_name='Кем хотите быть на teach.ua'),
        ),
    ]
