# Generated by Django 2.2.3 on 2019-07-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190725_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='../static/img/noimage.jpg', upload_to='media/', verbose_name='Фотография профиля'),
        ),
    ]
